import { TemplatePart, Template, Integration, Repository, Onboarding, Member, Event } from "@/types";

export const templateParts: TemplatePart[] = [
  {
    id: "1",
    title: "IDE Setup",
    description: "Configure your development environment with VS Code and essential extensions.",
    role: "intern",
    tags: ["setup", "tools"],
    fields: [
      { id: "f1", name: "ide_choice", label: "Preferred IDE", type: "select", required: true, options: ["VS Code", "IntelliJ", "Vim"] },
      { id: "f2", name: "extensions", label: "Installed Extensions", type: "textarea", required: false },
    ],
    validators: [
      { id: "v1", type: "command", os: ["mac", "linux"], params: { command: "code --version" } },
    ],
    updatedAt: "2025-10-09T10:30:00Z",
  },
  {
    id: "2",
    title: "CLI Tools Installation",
    description: "Install essential command-line tools: git, node, npm, and docker.",
    role: "intern",
    tags: ["setup", "cli"],
    fields: [
      { id: "f3", name: "git_version", label: "Git Version", type: "text", required: true },
      { id: "f4", name: "node_version", label: "Node Version", type: "text", required: true },
    ],
    validators: [
      { id: "v2", type: "command", os: ["mac", "linux", "win"], params: { command: "git --version" } },
      { id: "v3", type: "command", os: ["mac", "linux", "win"], params: { command: "node --version" } },
    ],
    updatedAt: "2025-10-08T14:20:00Z",
  },
  {
    id: "3",
    title: "Package Manager Setup",
    description: "Configure npm or yarn with company registry settings.",
    role: "intern",
    tags: ["setup", "npm"],
    fields: [
      { id: "f5", name: "package_manager", label: "Package Manager", type: "select", required: true, options: ["npm", "yarn", "pnpm"] },
    ],
    validators: [
      { id: "v4", type: "command", os: ["mac", "linux", "win"], params: { command: "npm config get registry" } },
    ],
    updatedAt: "2025-10-07T09:15:00Z",
  },
  {
    id: "4",
    title: "Repository Clone",
    description: "Clone the main project repository and verify access.",
    role: "manager",
    tags: ["git", "access"],
    fields: [
      { id: "f6", name: "repo_url", label: "Repository URL", type: "text", required: true },
      { id: "f7", name: "ssh_key", label: "SSH Key Fingerprint", type: "secret", required: true },
    ],
    validators: [
      { id: "v5", type: "command", os: ["mac", "linux"], params: { command: "git clone $REPO_URL" } },
    ],
    updatedAt: "2025-10-06T16:45:00Z",
  },
  {
    id: "5",
    title: "Environment Secrets",
    description: "Set up local environment variables and secrets for development.",
    role: "manager",
    tags: ["secrets", "config"],
    fields: [
      { id: "f8", name: "api_key", label: "API Key", type: "secret", required: true },
      { id: "f9", name: "db_connection", label: "DB Connection String", type: "secret", required: true },
    ],
    validators: [
      { id: "v6", type: "file", os: ["mac", "linux", "win"], params: { path: ".env" } },
    ],
    updatedAt: "2025-10-05T11:30:00Z",
  },
  {
    id: "6",
    title: "Jira Project Access",
    description: "Request and verify access to team Jira project.",
    role: "manager",
    tags: ["jira", "access"],
    fields: [
      { id: "f10", name: "jira_email", label: "Jira Email", type: "text", required: true },
      { id: "f11", name: "project_key", label: "Project Key", type: "text", required: true },
    ],
    validators: [
      { id: "v7", type: "http", os: ["mac", "linux", "win"], params: { url: "https://jira.company.com/api/project/$PROJECT_KEY" } },
    ],
    updatedAt: "2025-10-04T13:00:00Z",
  },
  {
    id: "7",
    title: "Linear Setup",
    description: "Join the Linear workspace and configure notifications.",
    role: "cto",
    tags: ["linear", "access"],
    fields: [
      { id: "f12", name: "linear_email", label: "Linear Email", type: "text", required: true },
    ],
    validators: [
      { id: "v8", type: "http", os: ["mac", "linux", "win"], params: { url: "https://api.linear.app/graphql" } },
    ],
    updatedAt: "2025-10-03T08:45:00Z",
  },
  {
    id: "8",
    title: "CI/CD Tokens",
    description: "Generate and configure personal access tokens for CI/CD pipelines.",
    role: "cto",
    tags: ["ci", "tokens"],
    fields: [
      { id: "f13", name: "github_token", label: "GitHub Token", type: "secret", required: true },
      { id: "f14", name: "gitlab_token", label: "GitLab Token", type: "secret", required: false },
    ],
    validators: [
      { id: "v9", type: "http", os: ["mac", "linux", "win"], params: { url: "https://api.github.com/user" } },
    ],
    updatedAt: "2025-10-02T15:20:00Z",
  },
];

export const templates: Template[] = [
  {
    id: "t1",
    name: "Intern Onboarding",
    version: "1.0.0",
    role: "intern",
    status: "published",
    steps: [
      { id: "s1", partId: "1", order: 0 },
      { id: "s2", partId: "2", order: 1 },
      { id: "s3", partId: "3", order: 2 },
    ],
    updatedAt: "2025-10-09T10:30:00Z",
  },
  {
    id: "t2",
    name: "Manager Onboarding",
    version: "1.2.0",
    role: "manager",
    status: "published",
    steps: [
      { id: "s4", partId: "1", order: 0 },
      { id: "s5", partId: "2", order: 1 },
      { id: "s6", partId: "4", order: 2 },
      { id: "s7", partId: "5", order: 3 },
      { id: "s8", partId: "6", order: 4 },
    ],
    updatedAt: "2025-10-08T14:20:00Z",
  },
  {
    id: "t3",
    name: "CTO Onboarding",
    version: "2.0.0",
    role: "cto",
    status: "published",
    steps: [
      { id: "s9", partId: "7", order: 0 },
      { id: "s10", partId: "8", order: 1 },
    ],
    updatedAt: "2025-10-07T09:15:00Z",
  },
  {
    id: "t4",
    name: "Intern V2 Draft",
    version: "2.0.0-draft",
    role: "intern",
    status: "draft",
    steps: [
      { id: "s11", partId: "1", order: 0 },
      { id: "s12", partId: "2", order: 1 },
    ],
    updatedAt: "2025-10-10T12:00:00Z",
  },
];

export const integrations: Integration[] = [
  {
    id: "github",
    name: "GitHub",
    icon: "github",
    description: "Connect to GitHub for repository scanning and access management.",
    connected: true,
    clientId: "gh_client_xxxxx",
    scopes: ["repo", "read:org"],
  },
  {
    id: "gitlab",
    name: "GitLab",
    icon: "gitlab",
    description: "Integrate GitLab repositories and CI/CD pipelines.",
    connected: false,
  },
  {
    id: "jira",
    name: "Jira",
    icon: "trello",
    description: "Sync Jira projects and track onboarding tasks.",
    connected: true,
    clientId: "jira_client_xxxxx",
    scopes: ["read:jira-work", "write:jira-work"],
  },
  {
    id: "linear",
    name: "Linear",
    icon: "layout",
    description: "Connect Linear for issue tracking and project management.",
    connected: false,
  },
  {
    id: "weaviate",
    name: "Weaviate",
    icon: "database",
    description: "Vector database for semantic search across documentation.",
    connected: false,
  },
  {
    id: "n8n",
    name: "N8N",
    icon: "workflow",
    description: "Workflow automation for custom onboarding flows.",
    connected: false,
  },
];

export const repositories: Repository[] = [
  {
    id: "r1",
    provider: "GitHub",
    org: "company",
    name: "main-app",
    defaultBranch: "main",
    lastScanStatus: "done",
    lastScanTime: "2025-10-10T08:30:00Z",
    artifacts: {
      dependencies: ["react@18.3.1", "typescript@5.0.0", "vite@5.0.0"],
      makefileTargets: ["build", "test", "deploy", "lint"],
      packageManagers: ["npm", "docker"],
    },
  },
];

export const onboardings: Onboarding[] = [
  {
    id: "o1",
    developerId: "dev1",
    developerName: "Alice Johnson",
    developerAvatar: "AJ",
    role: "intern",
    templateId: "t1",
    templateVersion: "1.0.0",
    progress: 67,
    status: "active",
    startedAt: "2025-10-09T09:00:00Z",
    updatedAt: "2025-10-11T14:30:00Z",
    steps: [
      { id: "os1", partId: "1", title: "IDE Setup", status: "passed" },
      { id: "os2", partId: "2", title: "CLI Tools Installation", status: "passed" },
      { id: "os3", partId: "3", title: "Package Manager Setup", status: "in_progress" },
    ],
  },
  {
    id: "o2",
    developerId: "dev2",
    developerName: "Bob Smith",
    developerAvatar: "BS",
    role: "manager",
    templateId: "t2",
    templateVersion: "1.2.0",
    progress: 40,
    status: "active",
    startedAt: "2025-10-08T10:00:00Z",
    updatedAt: "2025-10-11T11:15:00Z",
    steps: [
      { id: "os4", partId: "1", title: "IDE Setup", status: "passed" },
      { id: "os5", partId: "2", title: "CLI Tools Installation", status: "passed" },
      { id: "os6", partId: "4", title: "Repository Clone", status: "in_progress" },
      { id: "os7", partId: "5", title: "Environment Secrets", status: "not_started" },
      { id: "os8", partId: "6", title: "Jira Project Access", status: "not_started" },
    ],
  },
  {
    id: "o3",
    developerId: "dev3",
    developerName: "Carol Davis",
    developerAvatar: "CD",
    role: "intern",
    templateId: "t1",
    templateVersion: "1.0.0",
    progress: 33,
    status: "active",
    startedAt: "2025-10-10T11:30:00Z",
    updatedAt: "2025-10-11T09:45:00Z",
    steps: [
      { id: "os9", partId: "1", title: "IDE Setup", status: "passed" },
      { id: "os10", partId: "2", title: "CLI Tools Installation", status: "failed" },
      { id: "os11", partId: "3", title: "Package Manager Setup", status: "not_started" },
    ],
  },
  {
    id: "o4",
    developerId: "dev4",
    developerName: "David Wilson",
    developerAvatar: "DW",
    role: "cto",
    templateId: "t3",
    templateVersion: "2.0.0",
    progress: 100,
    status: "completed",
    startedAt: "2025-10-01T08:00:00Z",
    updatedAt: "2025-10-03T16:20:00Z",
    steps: [
      { id: "os12", partId: "7", title: "Linear Setup", status: "passed" },
      { id: "os13", partId: "8", title: "CI/CD Tokens", status: "passed" },
    ],
  },
  {
    id: "o5",
    developerId: "dev5",
    developerName: "Eva Martinez",
    developerAvatar: "EM",
    role: "intern",
    templateId: "t1",
    templateVersion: "1.0.0",
    progress: 100,
    status: "completed",
    startedAt: "2025-10-05T09:30:00Z",
    updatedAt: "2025-10-08T15:00:00Z",
    steps: [
      { id: "os14", partId: "1", title: "IDE Setup", status: "passed" },
      { id: "os15", partId: "2", title: "CLI Tools Installation", status: "passed" },
      { id: "os16", partId: "3", title: "Package Manager Setup", status: "passed" },
    ],
  },
  {
    id: "o6",
    developerId: "dev6",
    developerName: "Frank Chen",
    developerAvatar: "FC",
    role: "manager",
    templateId: "t2",
    templateVersion: "1.2.0",
    progress: 80,
    status: "active",
    startedAt: "2025-10-07T14:00:00Z",
    updatedAt: "2025-10-11T10:30:00Z",
    steps: [
      { id: "os17", partId: "1", title: "IDE Setup", status: "passed" },
      { id: "os18", partId: "2", title: "CLI Tools Installation", status: "passed" },
      { id: "os19", partId: "4", title: "Repository Clone", status: "passed" },
      { id: "os20", partId: "5", title: "Environment Secrets", status: "passed" },
      { id: "os21", partId: "6", title: "Jira Project Access", status: "in_progress" },
    ],
  },
];

export const members: Member[] = [
  { id: "m1", name: "Admin User", email: "admin@company.com", role: "admin", status: "active" },
  { id: "m2", name: "Alice Johnson", email: "alice@company.com", role: "dev", status: "active" },
  { id: "m3", name: "Bob Smith", email: "bob@company.com", role: "dev", status: "active" },
  { id: "m4", name: "Carol Davis", email: "carol@company.com", role: "dev", status: "pending" },
];

export const events: Event[] = [
  { id: "e1", timestamp: "2025-10-11T14:30:00Z", actor: "Alice Johnson", entity: "onboarding", action: "progressed", summary: "Completed Package Manager Setup" },
  { id: "e2", timestamp: "2025-10-11T11:15:00Z", actor: "Bob Smith", entity: "onboarding", action: "progressed", summary: "Started Repository Clone" },
  { id: "e3", timestamp: "2025-10-11T10:30:00Z", actor: "Frank Chen", entity: "onboarding", action: "progressed", summary: "Started Jira Project Access" },
  { id: "e4", timestamp: "2025-10-11T09:45:00Z", actor: "Carol Davis", entity: "onboarding", action: "failed", summary: "CLI Tools Installation validation failed" },
  { id: "e5", timestamp: "2025-10-10T16:00:00Z", actor: "Admin User", entity: "template", action: "created", summary: "Created draft template: Intern V2 Draft" },
  { id: "e6", timestamp: "2025-10-10T12:00:00Z", actor: "Admin User", entity: "scan", action: "completed", summary: "Repository scan completed for company/main-app" },
  { id: "e7", timestamp: "2025-10-10T11:30:00Z", actor: "Carol Davis", entity: "onboarding", action: "started", summary: "Started Intern Onboarding v1.0.0" },
  { id: "e8", timestamp: "2025-10-10T08:30:00Z", actor: "System", entity: "scan", action: "completed", summary: "Scheduled repository scan completed" },
];
